@baseUrl = http://localhost:3000
@applicantToken = PASTE_TOKEN_APPLICANT_DISINI

### Dashboard Applicant
GET {{baseUrl}}/api/dashboard
Authorization: Bearer {{applicantToken}}

### Lihat Profile Saya
GET {{baseUrl}}/api/profiles/me
Authorization: Bearer {{applicantToken}}

### Isi / Update Profile + Skills
PUT {{baseUrl}}/api/profiles/me
Authorization: Bearer {{applicantToken}}
Content-Type: application/json

{
  "fullName": "Budi Praintern",
  "location": "Bandung",
  "education": "S1 Informatika",
  "experienceYears": 1,
  "skills": ["nodejs", "mysql", "javascript"],
  "cvUrl": "https://example.com/cv.pdf"
}

### Lihat Lowongan (publik, tanpa token)
GET {{baseUrl}}/api/jobs

### Matching Job untuk Saya
GET {{baseUrl}}/api/matching/user
Authorization: Bearer {{applicantToken}}

### Melamar Kerja
POST {{baseUrl}}/api/applications
Authorization: Bearer {{applicantToken}}
Content-Type: application/json

{
  "job_id": 1
}

### Lihat Lamaran Saya
GET {{baseUrl}}/api/applications
Authorization: Bearer {{applicantToken}}

### Detail Lamaran
GET {{baseUrl}}/api/applications/1
Authorization: Bearer {{applicantToken}}

### Jadwal Interview Saya
GET {{baseUrl}}/api/interviews/my
Authorization: Bearer {{applicantToken}}
